# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.buttonLoadKdenlive = QtWidgets.QPushButton(self.centralwidget)
        self.buttonLoadKdenlive.setObjectName("buttonLoadKdenlive")
        self.horizontalLayout_2.addWidget(self.buttonLoadKdenlive)
        self.buttonLoadImages = QtWidgets.QPushButton(self.centralwidget)
        self.buttonLoadImages.setObjectName("buttonLoadImages")
        self.horizontalLayout_2.addWidget(self.buttonLoadImages)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.buttonSaveKdenlive = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSaveKdenlive.setObjectName("buttonSaveKdenlive")
        self.horizontalLayout_2.addWidget(self.buttonSaveKdenlive)
        self.buttonSaveBboxesJson = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSaveBboxesJson.setObjectName("buttonSaveBboxesJson")
        self.horizontalLayout_2.addWidget(self.buttonSaveBboxesJson)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineeditTargetVideoResolution = QtWidgets.QLineEdit(self.centralwidget)
        self.lineeditTargetVideoResolution.setText("")
        self.lineeditTargetVideoResolution.setObjectName("lineeditTargetVideoResolution")
        self.gridLayout.addWidget(self.lineeditTargetVideoResolution, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.image = ImageWidget(self.centralwidget)
        self.image.setObjectName("image")
        self.verticalLayout.addWidget(self.image)
        self.labelInfoPath = QtWidgets.QLabel(self.centralwidget)
        self.labelInfoPath.setObjectName("labelInfoPath")
        self.verticalLayout.addWidget(self.labelInfoPath)
        self.labelInfoScale = QtWidgets.QLabel(self.centralwidget)
        self.labelInfoScale.setObjectName("labelInfoScale")
        self.verticalLayout.addWidget(self.labelInfoScale)
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkboxStayInside = QtWidgets.QCheckBox(self.centralwidget)
        self.checkboxStayInside.setChecked(True)
        self.checkboxStayInside.setObjectName("checkboxStayInside")
        self.horizontalLayout.addWidget(self.checkboxStayInside)
        self.buttonSwitchInOutEditor = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSwitchInOutEditor.setObjectName("buttonSwitchInOutEditor")
        self.horizontalLayout.addWidget(self.buttonSwitchInOutEditor)
        self.buttonSwapInOutEditor = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSwapInOutEditor.setObjectName("buttonSwapInOutEditor")
        self.horizontalLayout.addWidget(self.buttonSwapInOutEditor)
        self.buttonImageNext = QtWidgets.QPushButton(self.centralwidget)
        self.buttonImageNext.setObjectName("buttonImageNext")
        self.horizontalLayout.addWidget(self.buttonImageNext)
        self.buttonImagePrev = QtWidgets.QPushButton(self.centralwidget)
        self.buttonImagePrev.setObjectName("buttonImagePrev")
        self.horizontalLayout.addWidget(self.buttonImagePrev)
        self.buttonDone = QtWidgets.QPushButton(self.centralwidget)
        self.buttonDone.setObjectName("buttonDone")
        self.horizontalLayout.addWidget(self.buttonDone)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.spinboxBboxRatioMultiplier = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spinboxBboxRatioMultiplier.setObjectName("spinboxBboxRatioMultiplier")
        self.horizontalLayout_3.addWidget(self.spinboxBboxRatioMultiplier)
        self.buttonApplyBboxRatioMultiplier = QtWidgets.QPushButton(self.centralwidget)
        self.buttonApplyBboxRatioMultiplier.setObjectName("buttonApplyBboxRatioMultiplier")
        self.horizontalLayout_3.addWidget(self.buttonApplyBboxRatioMultiplier)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout.setStretch(2, 3)
        self.verticalLayout.setStretch(5, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buttonLoadKdenlive.setText(_translate("MainWindow", "Load .kdenlive or bboxes .json"))
        self.buttonLoadImages.setText(_translate("MainWindow", "Load images"))
        self.buttonSaveKdenlive.setText(_translate("MainWindow", "Save .kdenlive"))
        self.buttonSaveBboxesJson.setText(_translate("MainWindow", "Save bboxes .json"))
        self.label.setText(_translate("MainWindow", "Target video resolution:"))
        self.labelInfoPath.setText(_translate("MainWindow", "InfoPath"))
        self.labelInfoScale.setText(_translate("MainWindow", "InfoScale"))
        self.checkboxStayInside.setText(_translate("MainWindow", "Stay Inside Image"))
        self.buttonSwitchInOutEditor.setText(_translate("MainWindow", "Switch In/Out Editor"))
        self.buttonSwapInOutEditor.setText(_translate("MainWindow", "Swap In/Out"))
        self.buttonImageNext.setText(_translate("MainWindow", "Next Image"))
        self.buttonImagePrev.setText(_translate("MainWindow", "Prev Image"))
        self.buttonDone.setText(_translate("MainWindow", "Done"))
        self.label_2.setText(_translate("MainWindow", "Set Bbox Ratio Multiplier:"))
        self.buttonApplyBboxRatioMultiplier.setText(_translate("MainWindow", "Apply"))


from image_widget import ImageWidget
