name: Kdenlive Slideshow Editor Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 # Updated to v4 (latest is generally better)
    - name: Set up Python 3.10
      uses: actions/setup-python@v4 # Updated to v4
      with:
        python-version: '3.10' # Added quotes as preferred by newer versions
    
    # Add this step to install system dependencies required for building packages like OpenTimelineIO
    - name: Install system dependencies for build
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake python3-dev
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel # Also good practice to ensure build tools are updated
        pip install -r requirements.txt
        pip install pytest
        
    - name: Test with pytest
      run: |
        pytest
